[tool.ruff]
line-length = 100
lint.ignore = ["D203"]


[tool.black]
line-length = 100
target-version = ['py310']

[tool.pytest.ini_options]
addopts = "-ra --cov"
testpaths = ["tests"]
pythonpath = ["."]
